
@AutoFieldTranslationExperiment_HostAddress = https://localhost:7101

GET {{AutoFieldTranslationExperiment_HostAddress}}/api/product
Accept: application/json

###
GET {{AutoFieldTranslationExperiment_HostAddress}}/api/product/7edad28b-cd3b-4301-6ae7-08dcefb989a5
Accept: application/json

###
POST {{AutoFieldTranslationExperiment_HostAddress}}/api/product
Content-Type: application/json
Accept: application/json

{
  "name": "Product 1"
}

###
PUT {{AutoFieldTranslationExperiment_HostAddress}}/api/product/1
Content-Type: application/json
Accept: application/json

{
  "name": "Product 1"
}

###
DELETE {{AutoFieldTranslationExperiment_HostAddress}}/api/product/7edad28b-cd3b-4301-6ae7-08dcefb989a5
Accept: application/json

###