
@AutoFieldTranslationExperiment_HostAddress = https://localhost:7101

GET {{AutoFieldTranslationExperiment_HostAddress}}/api/product
Accept: application/json
###
GET {{AutoFieldTranslationExperiment_HostAddress}}/api/product/1
Accept: application/json
###
POST {{AutoFieldTranslationExperiment_HostAddress}}/api/product
Content-Type: application/json
Accept: application/json

{
  "name": "Product 1",
}
###
PUT {{AutoFieldTranslationExperiment_HostAddress}}/api/product/1
Content-Type: application/json
Accept: application/json

{
  "name": "Product 1",
}
###